// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFiNeyxVtvuOBy6xScI_rfvNkUcf1EhY',
    appId: '1:378975756145:web:e6b1eedc732213209260d0',
    messagingSenderId: '378975756145',
    projectId: 'trippygo-2ecda',
    authDomain: 'trippygo-2ecda.firebaseapp.com',
    storageBucket: 'trippygo-2ecda.firebasestorage.app',
    measurementId: 'G-K651RB3YBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyiWinQge2bDYkGCh0aYFCvBjgKxvJn4',
    appId: '1:378975756145:android:986cb76c90ef78e39260d0',
    messagingSenderId: '378975756145',
    projectId: 'trippygo-2ecda',
    storageBucket: 'trippygo-2ecda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ONT5I51M0FA91D3E_MMOLECifCf4Q5Y',
    appId: '1:378975756145:ios:bf8458fef4db31529260d0',
    messagingSenderId: '378975756145',
    projectId: 'trippygo-2ecda',
    storageBucket: 'trippygo-2ecda.firebasestorage.app',
    iosBundleId: 'com.quantumbyte.trippygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ONT5I51M0FA91D3E_MMOLECifCf4Q5Y',
    appId: '1:378975756145:ios:bf8458fef4db31529260d0',
    messagingSenderId: '378975756145',
    projectId: 'trippygo-2ecda',
    storageBucket: 'trippygo-2ecda.firebasestorage.app',
    iosBundleId: 'com.quantumbyte.trippygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFiNeyxVtvuOBy6xScI_rfvNkUcf1EhY',
    appId: '1:378975756145:web:d6e617984838cd8a9260d0',
    messagingSenderId: '378975756145',
    projectId: 'trippygo-2ecda',
    authDomain: 'trippygo-2ecda.firebaseapp.com',
    storageBucket: 'trippygo-2ecda.firebasestorage.app',
    measurementId: 'G-HFY8CBEWKW',
  );
}
